# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from pages.bse_page import BasePage


class IncludeActionUi(BasePage):
    def __init__(self):
        super().__init__()
        self.listWidget = None

    def widget(self):
        widget = QtWidgets.QWidget()
        widget.setStyleSheet("background-color: red;")
        # widget.setGeometry(QtCore.QRect(90, 40, 211, 121))
        widget.setObjectName("widget")
        label = QtWidgets.QLabel(parent=widget)
        label.setGeometry(QtCore.QRect(30, 10, 54, 12))
        label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=widget)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 191, 81))
        self.listWidget.setObjectName("listWidget")

        return widget
