# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets

from pages.bse_page import BasePage


# 定义包含样式，比如循环中需要包含其他元素
class IncludeActionUi(BasePage):
    def __init__(self):
        super().__init__()
        self.listWidget = None

    def widget(self):
        widget = QtWidgets.QWidget()
        widget.setObjectName("include_widget")
        widget.setStyleSheet("background-color: white;")
        label = QtWidgets.QLabel(parent=widget)
        label.setGeometry(QtCore.QRect(30, 10, 54, 12))
        label.setText("名称")
        from pages.edit_action_list_view import ActionList
        self.listWidget = ActionList(parent=widget)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, widget.width() - 10, 20))
        widget.setFixedHeight(self.listWidget.height() + 40)
        return widget
